### PR TITLE
don't generate dogs at build time

### PR DESCRIPTION
**Pull request by Southclaws**

### CODE REVIEW

**Comment by Alasnkz** [comment]
🐕🐶🐕‍🦺🐩😭😥😢

**Comment by AmyrAhmady** [comment]
😞🙏🏻🐕🐶

**Comment by Southclaws** [comment]
https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation

we want `revalidate` and to load the md files into vercel somehow (they are ignored at the moment, which is why each page has a 404)

**Comment by Southclaws** [comment]
Okay so the pages aren't loaded into Vercel because that's just how Vercel works.

Instead, the docs are now served as raw markdown from https://api.open.mp/docs/ so for example https://api.open.mp/docs/index.md

So to finish this off, instead of readFileSync it should use fetch with the path appended to the api.

This should also kill two birds with one stone: Translation fallbacks (show English doc page and show a warning about it not being translated yet) should start working once this is done!

**Comment by Southclaws** [comment]
🐕🐕‍🦺🐶🐩

**Pull request merged**
