### PR TITLE
Better & responsive footer

### PR DESCRIPTION
**Pull request by ulasbayraktar**
I believe this footer would be more user-friendly and visually appealing. Additionally, I have made it responsive.

(updated)

image

image

### CODE REVIEW

**Comment by adib-yg** [comment]
Probably it's better to put omp logo above "About us" instead of center...

Also there's a duplicate of fb logo.

What is the button below "More" do?

**Comment by ulasbayraktar** [comment]
> there's a duplicate of fb logo.
> 
> What is the button below "More" do?

github and blog

**Comment by AmyrAhmady** [comment]
Blog icon is darker
SA-MP website link isn't there anymore
There are two facebook icons

**Comment by ulasbayraktar** [comment]
> Blog icon is darker
> 
> SA-MP website link isn't there anymore
> 
> There are two facebook icons

i will fix blog icon and two facebook icon 👍🏻

i should add samp website with icon?

**Comment by Southclaws** [comment]
image

I think we can remove the open.mp logo here on mobile, it's a bit too big and there's not much space for it and it doesn't really provide a lot of value. Perhaps the mobile one could be smaller (4x4em) and in the corner above or below the about text.

**Comment by ulasbayraktar** [comment]
> in the corner above or below the about text.

thank you Barnaby, its done

image

**Review by adib-yg — APPROVED** [review]

**Pull request merged**
