### PR TITLE
Operators and style added Fil trans

### PR DESCRIPTION
**Pull request by CnRXoMoX**

### CODE REVIEW

**Comment by Southclaws** [comment]
`fil` isn't an [ISO639-1](https://en.wikipedia.org/wiki/ISO_639-1) country code so this won't show in the translation list.

**Comment by CnRXoMoX** [comment]
> `fil` isn't an [ISO639-1](https://en.wikipedia.org/wiki/ISO_639-1) country code so this won't show in the translation list.

Yes, I used Ph as the country code nothing happens let me see if it will show now

**Comment by CnRXoMoX** [comment]
Mb, its tl

**Comment by CodeZulan** [comment]
> Mb, its tl

done

**Review by Southclaws — APPROVED** [review]

**Pull request merged**
