### PR TITLE
Fix and Update various callback information

### PR DESCRIPTION
**Pull request by ff-agus44**

### CODE REVIEW

**Review by Southclaws — APPROVED** [review]

**Comment by Southclaws** [comment]
Thank you for these fixes!

**Comment by ff-agus44** [comment]
It seems like i can push another one after ramadhan celebration ends (i think approx 2 days), sorry.

**Comment by Southclaws** [comment]
No problem, take your time and enjoy! :)

**Comment by ADRFranklin** [comment]
@ff-agus44 Are you still working on this, or is this dead?

**Pull request merged**
