### PR TITLE
Add open.mp launcher download button

### PR DESCRIPTION
**Pull request by FreddieCrew**
The title says it all: This PR adds the launcher download button to both the bottom and the header of the page.

### CODE REVIEW

**Comment by Southclaws** [comment]
@AmyrAhmady we at a point where this is good to put on the main site?

**Comment by AmyrAhmady** [comment]
@Southclaws Not yet, I have to finish launcher v1 first

**Comment by Southclaws** [comment]
Alright cool, in that case I'll leave this PR open and we can merge it or modify it when ready. Thanks @FreddieCrew for being proactive opening this! We'll get it merged at some point.

**Comment by FreddieCrew** [comment]
> Alright cool, in that case I'll leave this PR open and we can merge it or modify it when ready. Thanks @FreddieCrew for being proactive opening this! We'll get it merged at some point.

I'm happy to contribute, looking forward for the new release of the launcher.

**Review by adib-yg — CHANGES_REQUESTED** [review]

**Comment by adib-yg** [comment]
Version 1 of launcher is now published and this PR can be merged.

**Review by adib-yg — APPROVED** [review]

**Review by leonardssh — APPROVED** [review]

**Pull request merged**
