### PR TITLE
Pawn language guide

### PR DESCRIPTION
**Pull request by Southclaws**
Moved back to a branch because it broke somehow

### CODE REVIEW

**Comment by daddyDOT** [comment]
I don't really know what's happening with it. I was looking for some information in vercel deployment overview and it gives errors for things like "closing tag for <div>" or <hr> which it didn't used to give in the past, I used them many times but I dind't had an issue with it. Also, prettier suddenly stopped working for me, it doesn't want to format code idk why, maybe that gives some kind of issue.

**Comment by Southclaws** [comment]
I'm not sure what's wrong either. I tried to look into it but couldn't see the issue. I'll try again another day.

**Comment by daddyDOT** [comment]
@Southclaws I grabbed whole pawn-lang.md file and formatted it with prettier, changed some things like `<hr>` to `---`...
Should we let vercel check that one and try to merge it to see if the problem continues, I can make a new PR just for test?

**Comment by Southclaws** [comment]
Just push any changes to this branch. And build locally, it'll be faster than waiting for Vercel.

**Pull request merged**
