### PR TITLE
compliance with ISO-639-1

### PR DESCRIPTION
**Pull request by Dev-Zulan**

### CODE REVIEW

**Comment by Dev-Zulan** [comment]
reopening after open.mp website is fixed just to confirm

**Comment by Southclaws** [comment]
please reopen this as the actual site being offline doesn't matter, the changes can still be reviewed and merged ready for when the site is fully back

**Comment by Dev-Zulan** [comment]
Hello sorry for late response, I see now that there is tl (Wikang Tagalog) translation in the web but the translations are not shown, like OnPlayerDisconnect from the source (tl folder) is translated but in the site it's not, so I was wondering if it would work if I change to (fil)

**Review by Southclaws — APPROVED** [review]

**Comment by Southclaws** [comment]
Thanks for looking into this! It just needs a rebase on or merge with the master branch then it will auto merge

**Pull request merged**
