### PR TITLE
Change Twitter links & logo to X

### PR DESCRIPTION
**Pull request by pkfln**
Title says it all

### CODE REVIEW

**Comment by AmyrAhmady** [comment]
Show a screenshot of it first

**Review by Southclaws — APPROVED** [review]
looks good, but as amir said, screenshould would be great (we moved off vercel)

**Comment by pkfln** [comment]
Screenshot 2023-10-10 at 16 34 19
Screenshot 2023-10-10 at 16 34 30

**Review by leonardssh — APPROVED** [review]

**Comment by AmyrAhmady** [comment]
Looks a bit out of place and it's standing out compared to others. this is due to being next to a smaller icon YouTube, and the fact that X logo is trash and has a lot of spacing (which makes it *look* way bigger than the others)
maybe a filled & squared version of the logo works better, something like their iOS app icon, without the random noise and cracks in background

**Review by AmyrAhmady — CHANGES_REQUESTED** [review]
Looks a bit out of place and it's standing out compared to others. this is due to being next to a smaller icon YouTube, and the fact that X logo is trash and has a lot of spacing (which makes it look way bigger than the others)
maybe a filled & squared version of the logo works better, something like their iOS app icon, without the random noise and cracks in background

**Comment by pkfln** [comment]
Whoever is going to fix/adjust this, they can also fix the Discord and Facebook logos too, since they also look out of place. :)

**Comment by AmyrAhmady** [comment]
image
facebook looks fine

the X logo is just too different compared to others

**Comment by FreddieCrew** [comment]
I'm not sure if this change is even necessary because the new Twitter logo looks kinda meh. They basically just wrote an "X" with a fancy font. But, you know, it might be a good idea to approve this pr once and for all just to get it out of the way and keep the site up to date.

**Comment by Southclaws** [comment]
Fb vs insta is probably looking off due to the circles vs squares illusion: https://medium.com/design-bridges/optical-effects-9fca82b4cd9a

As for X, let's just merge and iterate if needed.

**Pull request merged**
