### PR TITLE
Merge 'pt' with 'pt-BR'

### PR DESCRIPTION
**Pull request by ArTDsL**
Talking with @iPollo we manage to discover that we are both working in same language, since the language sub is BR i decide to stay with the 'pt-BR' directory and copy all contents from 'PT', also change the CODEOWNERS file, and fix a litte problem at the end (a comma was add after a guy name).

I DO NOT replace any content already translated by @iPollo, i just add new files (translated by me)!

Please, aprove just after @iPollo revision!

### CODE REVIEW

**Review by leonardssh — APPROVED** [review]
LGTM! Waiting for @iPollo's decision. 🙂

**Review by Southclaws — APPROVED** [review]

**Review by iPollo — APPROVED** [review]

**Comment by iPollo** [comment]
Perfect :)

**Comment by leonardssh** [comment]
Great! @ArTDsL let me know when it's ready to merge. ☺️

**Comment by ArTDsL** [comment]
> Great! @ArTDsL let me know when it's ready to merge. ☺️

Hit the gas ^^!

**Pull request merged**
