### PR TITLE
some TR translations

### PR DESCRIPTION
**Pull request by psirograpth**

### CODE REVIEW

**Comment by lilAmper** [comment]
Bir dahakine gecikirse beni etiketlemeyi unutma.

**Review by lilAmper — APPROVED** [review]
Approved.

**Comment by Southclaws** [comment]
Just needs contributor license agreement signing, check the comment by CLAassistant above, hit the button and this will be merged. Thanks for your contribution!

**Review by lilAmper — APPROVED** [review]
Approved again.

**Pull request merged**
